import json
import requests

def generate_tactical_report(json_filepath="tactical_stats.json"):
    try:
        with open(json_filepath, 'r') as f:
            tactical_stats = json.load(f)
    except FileNotFoundError:
        return "Error: tactical_stats.json not found. Please run main.py first to generate the data."
        
    prompt = f"""
You are an expert football tactician and scout. Analyze this match data: 
{json.dumps(tactical_stats, indent=2)}

Identify which players are dominating possession, the overall team pace, and suggest three specific tactical counter-strategies to defeat Team 1.
Keep your response concise, structured, and easy to read for coaches.
"""

    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2",
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(url, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "No response generated by the model.")
    except Exception as e:
        return f"Error communicating with local LLM (Ollama): {str(e)}"

def generate_matchup_report(json_filepath, my_team_data, target_opponent_team):
    try:
        with open(json_filepath, 'r') as f:
            tactical_stats = json.load(f)
    except FileNotFoundError:
        return "Error: tactical_stats.json not found. Please run main.py first to generate the data."
        
    # Filter for the target opponent team
    opponent_players = [p for p in tactical_stats.get("players", []) if p.get("team") == target_opponent_team]
    opponent_possession = tactical_stats.get("team_possession", {}).get(f"team_{target_opponent_team}", "Unknown")
    
    prompt = f"""
You are an elite football tactical scout. 
Your goal is to provide a player-to-player match-up analysis and a tactical counter-strategy.

Here is the data for the OPPONENT team (Team {target_opponent_team}, Possession: {opponent_possession}) from their recent match video:
{json.dumps(opponent_players, indent=2)}

Here is MY TEAM's starting roster and stats:
{json.dumps(my_team_data, indent=2)}

Compare the key players, identify physical/speed mismatches, and suggest three specific tactical adjustments I should make to defeat this opponent using my specific roster.
Keep your response structured with markdown, concise, and easy to read for coaches.
"""

    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2",
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(url, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "No response generated by the model.")
    except Exception as e:
        return f"Error communicating with local LLM (Ollama): {str(e)}"

if __name__ == "__main__":
    report = generate_tactical_report()
    print("=== TACTICAL SCOUTING REPORT ===")
    print(report)
